### ISSUE TITLE
confusing on "creates hosts files"

### ISSUE THREAD

**Issue by wzdutd** [dkozlov/openfaas-tensorflow-gpu#1]
Hello, Dkozlov,

Thank you for your code. It's really helpful. However, I was confused with the part "creates hosts files". Should I go to the directory "/etc/" where the hosts file located？Also, what does "[gpus : vars]" indicate? Can you give me any feedback, please? I really appreciated it.

Thanks again!
Best
wzhend

**Comment by dkozlov** [comment]
Hello, Wzhend!

Under "create hosts file" I mean that you need to create [Ansible Host Inventory](https://ansible-tips-and-tricks.readthedocs.io/en/latest/ansible/inventory/). Thank you, I will update this information in readme.md.  Please feel free to ask any questions if you have them.

Best regards,
Dmitry Kozlov
