### ISSUE TITLE
unreachable when performing initial configuration by Ansible, install ... 

### ISSUE THREAD

**Issue by wzdutd** [dkozlov/openfaas-tensorflow-gpu#2]
Hello, Dkozlov,

Thank you for your help. I was caught by a new issue,

I run an AWS EC2 instance and configure the hosts file as you indicated (" Add previously created GPU hostname "). However, when I implemented the command "ansible-playbook gpus.yml", it responded ""changed": false, "msg": "SSH Error: data could not be sent to remote host \"".

What do you think about the possible reasons? Currently, I am remotely accessing a server to run your code using MobaXterm. In my opinion, it may be caused that I didn't configure .ssh directly/file correctly. I tried to solve the problem, but it doesn't work as well. Can you give me any feedback, please? I really appreciated it.

Best
wzhend

**Comment by dkozlov** [comment]
Hello Wzhend,
You need to check that the SSH key related to the EC2 instance from AWS is properly configured and have right permission https://github.com/dkozlov/openfaas-tensorflow-gpu#download-aws-ec2-private-key-to-ssh. See the following guide about SSH keys on AWS: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html

**Comment by wzdutd** [comment]
Hello, Dkozlov
Thank you for your reply. You're so nice. I will do as you instructed.

Thanks again
Best
wzhend
