### ISSUE TITLE
can I deploy the openfaas-tensorflow-gpu using minikube?

### ISSUE THREAD

**Issue by wzdutd** [dkozlov/openfaas-tensorflow-gpu#3]
Hello, dkozlov,

Thank you for your nice work. I wondered whether I can deploy openfaas-tensorflow-gpu
using minikube instead of complete kubenetes. Besides, is there any requirement on the GPU type/power?

Thank you,
Best,
Zhendong

**Comment by dkozlov** [comment]
Hello Wzhend,
I think that 'ssd_mobilenet_v1_coco_2017_11_17' model could work even on CPU. Unfortunately I have not tested openfaas using minikube.
